<?
$grouppermit['GroupName']='Visitor';
$grouppermit['ViewUserDetail']=0;
$grouppermit['ViewUserList']=1;
$grouppermit['ViewStat']=0;
$grouppermit['ViewGallery']=1;
$grouppermit['ViewPic']=1;
$grouppermit['BasicSearch']=1;
$grouppermit['AdvancedSearch']=0;
$grouppermit['ViewLinks']=1;
$grouppermit['AddGuestbook']=1;
$grouppermit['AddComment']=1;
$grouppermit['AdvancedUBB']=0;
