#!/bin/bash
# $1:  xxxxxx
# 插件说明：
# 当双击打开对话窗口时，系统将调用此插件，调用的第一个参数为：
# xxxxxx: 对方飞信号或者对方手机号
buddy=$1

#该插件自动发送演示信息

message="<Font Face='仿宋' Color='-8388608' Size='12'>欢迎实用飞信股票！</Font>"

cmd="chat $buddy $message"

# 最后，请以 回车结束
echo $cmd
